version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/using-orbs/
orbs:
  ruby: circleci/ruby@1.0

jobs:
  test:  # our next job, called "test"
    docker:
      - image: cimg/ruby:2.6.5 # this is our docker image, where step commands run.
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    # A series of steps to run
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Compile C++ extension
          command: 'bundle exec rake compile'
      - ruby/rspec-test

# We use workflows to orchestrate the jobs that we declared above.
workflows:
  version: 2
  test:     # The name of our workflow
    jobs:             # The list of jobs we run as part of this workflow.
      - test
